[[redirects]]
from = "https://module-4-ciceiy.netlify.app/categories"
to = "http://localhost:3001/categories/:splat"
status = 200
force = true

[[redirects]]
from = "https://module-4-ciceiy.netlify.app/login"
to = "http://localhost:3001/login/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200